version: "3.8"

services:
  # 1. MySQL Database
  db:
    image: mysql:8.0
    container_name: fcdbb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: football_db
    ports:
      - "3306:3306" # Map port ra ngoài để DataGrip kết nối được
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-proot123",
        ]
      timeout: 20s
      retries: 10

  # 2. Backend API
  api:
    build:
      context: .
      dockerfile: server/Dockerfile # (Tạo file này bên dưới)
    container_name: fcdbb-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db # Trong mạng Docker, host là tên service 'db'
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=football_db
      - JWT_SECRET=bi_mat_khong_the_bat_mi_cua_lunu
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
